ホーム画面の投稿のcellを作成、接続しました。
Reon0429-cat/PetSNS pull request #75
Opened 2021-08-27 23:19 UTC by sagaraEito

#38 
ホーム画面の投稿のcellを作成、接続しました。
また、messageButtonに関しては状態の変更などの処理が思いつかなかったためoutlet接続していません。
<img width="811" alt="スクリーンショット 2021-08-28 8 06 03" src="https://user-images.githubusercontent.com/69618315/131197416-20ccce18-a3c1-4d0c-97f9-9c3eb982d988.png">

2021-08-27 23:59 UTC, tatsuya-ss requested changes
1. ImageViewとTextViewの横の制約はどっちか片方とCenter Horizontally使った方がいいかもしれないです。
2. 写真動画表示はUIImageViewとUIViewのやり方があるみたいです。draw.ioの時ReonさんがUIViewと言ってた記憶があるので、確認してみてください。どちらでも良いのかもしれませんが。
3. xib作成時は、フォルダ分けするのかどうかも決めていなかったと思うので、確認お願いします。

2021-08-28 06:34 UTC, sagaraEito commented
@Reon0429-cat 
@tatsuya-ss 
修正しました。
改めてご確認よろしくお願いします。

2021-08-28 06:43 UTC, Reon0429-cat approved these changes
![image](https://user-images.githubusercontent.com/66917548/131209115-e5e7dbd5-8a65-4ef3-889b-58af6a7b03b7.png)

2021-08-28 06:53 UTC, tatsuya-ss approved these changes
いいと思います！

2021-08-28 06:54 UTC, merged